### ISSUE TITLE
'composer require' inconsistency with user guide

### ISSUE THREAD

**Issue by effinrobots** [leafsphp/bareui#1]
When following the user guide, using 'composer require leafs/bareui' the version that is installed is the 1.0 release, which doesn't appear to include the functionality for global template 'params'. I had to require bareui dev-main in order to get the latest version- just an inconsistency with the guide that caused quite a bit of confusion.

**Comment by mychidarko** [comment]
Hi @effinrobots thanks for pointing this out. A new version has been released which fixes this issue.
